# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://localhost:8080/api/user/users
Accept: application/json

###

DELETE http://localhost:8080/api/user/delete/4
Accept: application/json
###

PUT http://localhost:8080/api/user/modify
Content-Type: application/json

{
  "id": "1",
  "account": "Ttolz",
  "username": "TooltaToolta",
  "email": "Kanaria@xml.go"
}


###

POST http://localhost:8080/api/user/join
Content-Type: application/json

{
  "account": "KIRBY",
  "username": "POPSTAR",
  "email": "Green@Gree.ns"
}
###

GET http://localhost:8080/api/user/1
Accept: application/json

###









GET http://localhost:8080/api/post/posts
Accept: application/json


###

GET http://localhost:8080/api/post/postu/1
Accept: application/json

###

DELETE http://localhost:8080/api/post/delete/3
Accept: application/json

###

POST http://localhost:8080/api/post/write/h
Content-Type: application/json

{
  "userId": "3",
  "title": "HOWHOW",
  "content": "Drodi ORIYA"
}
###

GET http://localhost:8080/api/post/find/4
Accept: application/json

###

PUT http://localhost:8080/api/post/modify
Content-Type: application/json

{
  "id": "7",
  "title": "fixed Title",
  "content": "freeeeeeeeeeeeeeeeeeee"
}
###